### ISSUE TITLE
Non-stop "Initialising Search Index"

### ISSUE THREAD

**Issue by arthur-albuquerque** [deanishe/zothero#51]
Hi, I just downloaded ZotHero and I might be doing something wrong. It just doesn't find any of my citations. Would you please help me?

**Comment by masteranza** [comment]
Same here. We need a fix 😢

**Comment by jacob-moses** [comment]
I'm having the same issue. Using: Zotero 1.3.0, Alfred 4.3.1, Zotero 5, Better BibTex 5.2.117

**Comment by AragornYY** [comment]
Same here.
The log is following.

```
OperationalError: database is locked
16:16:00 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/zothero/issues
16:16:00 core.py:197 INFO     [core] searching for "log" ...
16:16:00 index.py:245 INFO     [index] 0 result(s) for u'log'
16:16:01 core.py:197 INFO     [core] searching for "log" ...
16:16:01 index.py:245 INFO     [index] 0 result(s) for u'log'
16:16:01 core.py:197 INFO     [core] searching for "lo" ...
16:16:01 index.py:245 INFO     [index] 0 result(s) for u'lo'
16:16:01 core.py:197 INFO     [core] searching for "lo" ...
16:16:01 index.py:245 INFO     [index] 0 result(s) for u'lo'
16:16:01 core.py:197 INFO     [core] searching for "l" ...
16:16:01 index.py:245 INFO     [index] 0 result(s) for u'l'
16:16:06 workflow.py:2080 ERROR    database is locked
Traceback (most recent call last):
  File "./lib/workflow/workflow.py", line 2073, in run
    func(self)
  File "./zh", line 714, in main
    return do_reindex()
  File "./zh", line 597, in do_reindex
    app.update_index(force=False)
  File "./lib/zothero/core.py", line 166, in update_index
    self.index.update(self.zotero, force)
  File "./lib/zothero/index.py", line 277, in update
    if not self._update(zot, force):
  File "./lib/zothero/index.py", line 325, in _update
    for e in it:
  File "./lib/zothero/zotero.py", line 268, in all_entries
    yield self._load_entry(row)
  File "./lib/zothero/zotero.py", line 320, in _load_entry
    e.citekey = self.bbt.citekey('{}_{}'.format(e.library, e.key))
  File "./lib/zothero/zotero.py", line 195, in bbt
    self._bbt = BetterBibTex(self.datadir)
  File "./lib/zothero/betterbibtex.py", line 48, in __init__
    row = conn.execute(SQL).fetchone()
OperationalError: database is locked
16:16:06 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/zothero/issues
```

**Comment by AragornYY** [comment]
It works if Better BibTex is disabled in Zotero.
This seems to be an issue for Better BibTex rather than Zothero.

**Comment by twio142** [comment]
Same here. Have to restart Zotero every time for any changes to the libraries to be synced in the workflow.

**Comment by Miaoyifei-mz** [comment]
When I update Better BibTex to 5.2.138（The latest version，the problem goes away.(*^▽^*)

**Comment by dr-gu** [comment]
My Better BibTex version is 5.4.5, but this problem remains unsolved.

**Comment by raivivek** [comment]
Restarting Zotero (quit, wait a few seconds, and reopen) should fix it.
